<?php

namespace Database\Seeders;

use App\Models\Menu;
use Illuminate\Database\Seeder;

class MenuSeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
                'parent_id' => null,
                'name' => 'Settings',
                'url' => 'setting',
                'icon' => 'fe-settings',
                'prefix' => 'setting',
                'permission_name' => 'setting',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'parent_id' => 1,
                'name' => 'Menu Management',
                'url' => 'menu.index',
                'icon' => 'fe-circle',
                'prefix' => 'setting',
                'permission_name' => 'menu',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'parent_id' => 1,
                'name' => 'Role Management',
                'url' => 'role.index',
                'icon' => 'fe-circle',
                'prefix' => 'setting',
                'permission_name' => 'role',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'parent_id' => 1,
                'name' => 'User Management',
                'url' => 'user.index',
                'icon' => 'fe-circle',
                'prefix' => 'setting',
                'permission_name' => 'user',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'parent_id' => null,
                'name' => 'Master Data',
                'url' => 'data',
                'icon' => 'fe-cpu',
                'prefix' => 'data',
                'permission_name' => 'data',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'parent_id' => 5,
                'name' => 'Data Wilayah',
                'url' => 'region.index',
                'icon' => 'fe-circle',
                'prefix' => 'data',
                'permission_name' => 'region',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'parent_id' => 5,
                'name' => 'Data Kecamatan',
                'url' => 'district.index',
                'icon' => 'fe-circle',
                'prefix' => 'data',
                'permission_name' => 'district',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'parent_id' => 5,
                'name' => 'Data Desa/Kelurahan',
                'url' => 'village.index',
                'icon' => 'fe-circle',
                'prefix' => 'data',
                'permission_name' => 'village',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'parent_id' => 5,
                'name' => 'Data TPS',
                'url' => 'tps.index',
                'icon' => 'fe-circle',
                'prefix' => 'data',
                'permission_name' => 'tps',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'parent_id' => null,
                'name' => 'One Supporting',
                'url' => 'one.index',
                'icon' => 'fe-codepen',
                'prefix' => 'one',
                'permission_name' => 'one',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'parent_id' => null,
                'name' => 'Data Dukungan',
                'url' => 'voter.index',
                'icon' => 'fe-check-square',
                'prefix' => 'voter',
                'permission_name' => 'voter',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'parent_id' => null,
                'name' => 'Logistik',
                'url' => 'logistic',
                'icon' => 'fe-grid',
                'prefix' => 'logistic',
                'permission_name' => 'logistic',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'parent_id' => 12,
                'name' => 'Permintaan Barang',
                'url' => 'request.index',
                'icon' => 'fe-circle',
                'prefix' => 'logistic',
                'permission_name' => 'request',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'parent_id' => 12,
                'name' => 'Kategori Barang',
                'url' => 'category.index',
                'icon' => 'fe-circle',
                'prefix' => 'logistic',
                'permission_name' => 'category',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'parent_id' => 12,
                'name' => 'Daftar Barang',
                'url' => 'product.index',
                'icon' => 'fe-circle',
                'prefix' => 'logistic',
                'permission_name' => 'product',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'parent_id' => 12,
                'name' => 'Stok Barang',
                'url' => 'stock.index',
                'icon' => 'fe-circle',
                'prefix' => 'logistic',
                'permission_name' => 'stock',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'parent_id' => 12,
                'name' => 'Laporan',
                'url' => 'report.index',
                'icon' => 'fe-circle',
                'prefix' => 'logistic',
                'permission_name' => 'report',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'parent_id' => null,
                'name' => 'Rekapitulasi',
                'url' => 'recapitulation.index',
                'icon' => 'fe-file-text',
                'prefix' => 'recapitulation',
                'permission_name' => 'recapitulation',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($data as $row) {
            Menu::insert($row);
        }
    }
}
