<?php

namespace Database\Seeders;

use App\Models\Village;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class VillageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            ['village_name' => 'Cinennung', 'village_type' => 'Desa', 'district_id' => 1, 'user_id' => null, 'voter_2014' => 12, 'voter_2019' => 18, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Siame', 'village_type' => 'Desa', 'district_id' => 1, 'user_id' => null, 'voter_2014' => 26, 'voter_2019' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Passempe', 'village_type' => 'Desa', 'district_id' => 1, 'user_id' => null, 'voter_2014' => 98, 'voter_2019' => 23, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Ureng', 'village_type' => 'Desa', 'district_id' => 1, 'user_id' => null, 'voter_2014' => 42, 'voter_2019' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Usa', 'village_type' => 'Desa', 'district_id' => 1, 'user_id' => null, 'voter_2014' => 62, 'voter_2019' => 15, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Mico', 'village_type' => 'Desa', 'district_id' => 1, 'user_id' => null, 'voter_2014' => 38, 'voter_2019' => 149, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Bainang', 'village_type' => 'Desa', 'district_id' => 1, 'user_id' => null, 'voter_2014' => 14, 'voter_2019' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Passippo', 'village_type' => 'Desa', 'district_id' => 1, 'user_id' => null, 'voter_2014' => 61, 'voter_2019' => 15, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Tanah Tengah', 'village_type' => 'Desa', 'district_id' => 1, 'user_id' => null, 'voter_2014' => 16, 'voter_2019' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Tirong', 'village_type' => 'Desa', 'district_id' => 1, 'user_id' => null, 'voter_2014' => 12, 'voter_2019' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Mattanete Bua', 'village_type' => 'Desa', 'district_id' => 1, 'user_id' => null, 'voter_2014' => 9, 'voter_2019' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Maduri', 'village_type' => 'Desa', 'district_id' => 1, 'user_id' => null, 'voter_2014' => 11, 'voter_2019' => 33, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Melle', 'village_type' => 'Desa', 'district_id' => 1, 'user_id' => null, 'voter_2014' => 25, 'voter_2019' => 56, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Lemo Ape', 'village_type' => 'Desa', 'district_id' => 1, 'user_id' => null, 'voter_2014' => 50, 'voter_2019' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Panyili', 'village_type' => 'Desa', 'district_id' => 1, 'user_id' => null, 'voter_2014' => 11, 'voter_2019' => 45, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Biru', 'village_type' => 'Kelurahan', 'district_id' => 2, 'user_id' => null, 'voter_2014' => 469, 'voter_2019' => 323, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Ta', 'village_type' => 'Kelurahan', 'district_id' => 2, 'user_id' => null, 'voter_2014' => 225, 'voter_2019' => 136, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Watampone', 'village_type' => 'Kelurahan', 'district_id' => 2, 'user_id' => null, 'voter_2014' => 78, 'voter_2019' => 124, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Bukaka', 'village_type' => 'Kelurahan', 'district_id' => 2, 'user_id' => null, 'voter_2014' => 59, 'voter_2019' => 109, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Pappolo', 'village_type' => 'Kelurahan', 'district_id' => 2, 'user_id' => null, 'voter_2014' => 56, 'voter_2019' => 29, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Manurunge', 'village_type' => 'Kelurahan', 'district_id' => 2, 'user_id' => null, 'voter_2014' => 158, 'voter_2019' => 159, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Walannae', 'village_type' => 'Kelurahan', 'district_id' => 2, 'user_id' => null, 'voter_2014' => 56, 'voter_2019' => 24, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Masumpu', 'village_type' => 'Kelurahan', 'district_id' => 2, 'user_id' => null, 'voter_2014' => 210, 'voter_2019' => 178, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Macege', 'village_type' => 'Kelurahan', 'district_id' => 3, 'user_id' => null, 'voter_2014' => 119, 'voter_2019' => 144, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Mattiro Walie', 'village_type' => 'Kelurahan', 'district_id' => 3, 'user_id' => null, 'voter_2014' => 36, 'voter_2019' => 69, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Macanang', 'village_type' => 'Kelurahan', 'district_id' => 3, 'user_id' => null, 'voter_2014' => 93, 'voter_2019' => 177, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Majang', 'village_type' => 'Kelurahan', 'district_id' => 3, 'user_id' => null, 'voter_2014' => 36, 'voter_2019' => 29, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Bulu Tempe', 'village_type' => 'Kelurahan', 'district_id' => 3, 'user_id' => null, 'voter_2014' => 56, 'voter_2019' => 95, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Jeppee', 'village_type' => 'Kelurahan', 'district_id' => 3, 'user_id' => null, 'voter_2014' => 77, 'voter_2019' => 114, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Polewali', 'village_type' => 'Kelurahan', 'district_id' => 3, 'user_id' => null, 'voter_2014' => 33, 'voter_2019' => 34, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Watang Palakka', 'village_type' => 'Kelurahan', 'district_id' => 3, 'user_id' => null, 'voter_2014' => 27, 'voter_2019' => 47, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Bajoe', 'village_type' => 'Kelurahan', 'district_id' => 4, 'user_id' => null, 'voter_2014' => 67, 'voter_2019' => 83, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Cellu', 'village_type' => 'Kelurahan', 'district_id' => 4, 'user_id' => null, 'voter_2014' => 42, 'voter_2019' => 44, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Panyula', 'village_type' => 'Kelurahan', 'district_id' => 4, 'user_id' => null, 'voter_2014' => 66, 'voter_2019' => 124, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Waetuo', 'village_type' => 'Kelurahan', 'district_id' => 4, 'user_id' => null, 'voter_2014' => 46, 'voter_2019' => 130, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Pallette', 'village_type' => 'Kelurahan', 'district_id' => 4, 'user_id' => null, 'voter_2014' => 7, 'voter_2019' => 105, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Tibojong', 'village_type' => 'Kelurahan', 'district_id' => 4, 'user_id' => null, 'voter_2014' => 128, 'voter_2019' => 104, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Toro', 'village_type' => 'Kelurahan', 'district_id' => 4, 'user_id' => null, 'voter_2014' => 199, 'voter_2019' => 112, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Lonrae', 'village_type' => 'Kelurahan', 'district_id' => 4, 'user_id' => null, 'voter_2014' => 204, 'voter_2019' => 84, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Padaelo', 'village_type' => 'Kelurahan', 'district_id' => 5, 'user_id' => null, 'voter_2014' => 55, 'voter_2019' => 42, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Mattiro Walie', 'village_type' => 'Desa', 'district_id' => 5, 'user_id' => null, 'voter_2014' => 1, 'voter_2019' => 62, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Mario', 'village_type' => 'Desa', 'district_id' => 5, 'user_id' => null, 'voter_2014' => 90, 'voter_2019' => 144, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Ujung Salangketo', 'village_type' => 'Desa', 'district_id' => 5, 'user_id' => null, 'voter_2014' => 87, 'voter_2019' => 73, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Tellu Boccoe', 'village_type' => 'Desa', 'district_id' => 5, 'user_id' => null, 'voter_2014' => 112, 'voter_2019' => 79, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Mattampa Walie', 'village_type' => 'Desa', 'district_id' => 5, 'user_id' => null, 'voter_2014' => 14, 'voter_2019' => 19, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Ujung Tanah', 'village_type' => 'Desa', 'district_id' => 5, 'user_id' => null, 'voter_2014' => 46, 'voter_2019' => 38, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Sumaling', 'village_type' => 'Desa', 'district_id' => 5, 'user_id' => null, 'voter_2014' => 18, 'voter_2019' => 38, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Tellongeng', 'village_type' => 'Desa', 'district_id' => 5, 'user_id' => null, 'voter_2014' => 40, 'voter_2019' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Data', 'village_type' => 'Desa', 'district_id' => 5, 'user_id' => null, 'voter_2014' => 18, 'voter_2019' => 19, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Batu Gading', 'village_type' => 'Desa', 'district_id' => 5, 'user_id' => null, 'voter_2014' => 34, 'voter_2019' => 46, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Cege', 'village_type' => 'Desa', 'district_id' => 5, 'user_id' => null, 'voter_2014' => 24, 'voter_2019' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Kadai', 'village_type' => 'Desa', 'district_id' => 5, 'user_id' => null, 'voter_2014' => 77, 'voter_2019' => 78, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Lakukang', 'village_type' => 'Desa', 'district_id' => 5, 'user_id' => null, 'voter_2014' => 12, 'voter_2019' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Pattiro', 'village_type' => 'Desa', 'district_id' => 5, 'user_id' => null, 'voter_2014' => 14, 'voter_2019' => 33, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Lapasa', 'village_type' => 'Desa', 'district_id' => 5, 'user_id' => null, 'voter_2014' => 80, 'voter_2019' => 29, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Karella', 'village_type' => 'Desa', 'district_id' => 5, 'user_id' => null, 'voter_2014' => 7, 'voter_2019' => 113, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Lappa Upang', 'village_type' => 'Desa', 'district_id' => 5, 'user_id' => null, 'voter_2014' => 22, 'voter_2019' => 139, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Maroanging', 'village_type' => 'Kelurahan', 'district_id' => 6, 'user_id' => null, 'voter_2014' => 11, 'voter_2019' => 31, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Pattiro Bajo', 'village_type' => 'Desa', 'district_id' => 6, 'user_id' => null, 'voter_2014' => 11, 'voter_2019' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Massenreng Pulu', 'village_type' => 'Desa', 'district_id' => 6, 'user_id' => null, 'voter_2014' => 3, 'voter_2019' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Tunreng Tellue', 'village_type' => 'Desa', 'district_id' => 6, 'user_id' => null, 'voter_2014' => 29, 'voter_2019' => 34, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Polewali', 'village_type' => 'Desa', 'district_id' => 6, 'user_id' => null, 'voter_2014' => 13, 'voter_2019' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Tadang Palie', 'village_type' => 'Desa', 'district_id' => 6, 'user_id' => null, 'voter_2014' => 14, 'voter_2019' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Cinnong', 'village_type' => 'Desa', 'district_id' => 6, 'user_id' => null, 'voter_2014' => 72, 'voter_2019' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Mallusetasi', 'village_type' => 'Desa', 'district_id' => 6, 'user_id' => null, 'voter_2014' => 25, 'voter_2019' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Pakkasalo', 'village_type' => 'Desa', 'district_id' => 6, 'user_id' => null, 'voter_2014' => 10, 'voter_2019' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Pattiro Sompe', 'village_type' => 'Desa', 'district_id' => 6, 'user_id' => null, 'voter_2014' => 35, 'voter_2019' => 46, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Ajang Pulu', 'village_type' => 'Desa', 'district_id' => 6, 'user_id' => null, 'voter_2014' => 15, 'voter_2019' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Sumpang Minangae', 'village_type' => 'Desa', 'district_id' => 6, 'user_id' => null, 'voter_2014' => 7, 'voter_2019' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Mabbiring', 'village_type' => 'Desa', 'district_id' => 6, 'user_id' => null, 'voter_2014' => 27, 'voter_2019' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Pasaka', 'village_type' => 'Desa', 'district_id' => 6, 'user_id' => null, 'voter_2014' => 29, 'voter_2019' => 39, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Kalibbong', 'village_type' => 'Desa', 'district_id' => 6, 'user_id' => null, 'voter_2014' => 12, 'voter_2019' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Pattiro Riolo', 'village_type' => 'Desa', 'district_id' => 6, 'user_id' => null, 'voter_2014' => 114, 'voter_2019' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Letta Tanah', 'village_type' => 'Desa', 'district_id' => 6, 'user_id' => null, 'voter_2014' => 10, 'voter_2019' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Manajeng', 'village_type' => 'Desa', 'district_id' => 6, 'user_id' => null, 'voter_2014' => 17, 'voter_2019' => 47, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Bulie', 'village_type' => 'Desa', 'district_id' => 6, 'user_id' => null, 'voter_2014' => 14, 'voter_2019' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Balieng Toa', 'village_type' => 'Desa', 'district_id' => 6, 'user_id' => null, 'voter_2014' => 52, 'voter_2019' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Bacu', 'village_type' => 'Desa', 'district_id' => 7, 'user_id' => null, 'voter_2014' => 3, 'voter_2019' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Lampoko', 'village_type' => 'Desa', 'district_id' => 7, 'user_id' => null, 'voter_2014' => 12, 'voter_2019' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Congko', 'village_type' => 'Desa', 'district_id' => 7, 'user_id' => null, 'voter_2014' => 62, 'voter_2019' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Wollangi', 'village_type' => 'Desa', 'district_id' => 7, 'user_id' => null, 'voter_2014' => 0, 'voter_2019' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Parippung', 'village_type' => 'Desa', 'district_id' => 7, 'user_id' => null, 'voter_2014' => 20, 'voter_2019' => 28, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Apala', 'village_type' => 'Desa', 'district_id' => 7, 'user_id' => null, 'voter_2014' => 63, 'voter_2019' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Barebbo', 'village_type' => 'Desa', 'district_id' => 7, 'user_id' => null, 'voter_2014' => 29, 'voter_2019' => 22, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Kading', 'village_type' => 'Desa', 'district_id' => 7, 'user_id' => null, 'voter_2014' => 55, 'voter_2019' => 54, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Kajaolaliddong', 'village_type' => 'Desa', 'district_id' => 7, 'user_id' => null, 'voter_2014' => 103, 'voter_2019' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Samaelo', 'village_type' => 'Desa', 'district_id' => 7, 'user_id' => null, 'voter_2014' => 19, 'voter_2019' => 28, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Corawalie', 'village_type' => 'Desa', 'district_id' => 7, 'user_id' => null, 'voter_2014' => 111, 'voter_2019' => 48, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Talungeng', 'village_type' => 'Desa', 'district_id' => 7, 'user_id' => null, 'voter_2014' => 6, 'voter_2019' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Watu', 'village_type' => 'Desa', 'district_id' => 7, 'user_id' => null, 'voter_2014' => 34, 'voter_2019' => 44, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Cingkang', 'village_type' => 'Desa', 'district_id' => 7, 'user_id' => null, 'voter_2014' => 8, 'voter_2019' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Cinnong', 'village_type' => 'Desa', 'district_id' => 7, 'user_id' => null, 'voter_2014' => 4, 'voter_2019' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Cempaniga', 'village_type' => 'Desa', 'district_id' => 7, 'user_id' => null, 'voter_2014' => 0, 'voter_2019' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Sugiale', 'village_type' => 'Desa', 'district_id' => 7, 'user_id' => null, 'voter_2014' => 43, 'voter_2019' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Kampuno', 'village_type' => 'Desa', 'district_id' => 7, 'user_id' => null, 'voter_2014' => 26, 'voter_2019' => 25, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Tanete', 'village_type' => 'Kelurahan', 'district_id' => 8, 'user_id' => null, 'voter_2014' => 10, 'voter_2019' => 65, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Arasoe', 'village_type' => 'Desa', 'district_id' => 8, 'user_id' => null, 'voter_2014' => 21, 'voter_2019' => 33, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Tanete Harapan', 'village_type' => 'Desa', 'district_id' => 8, 'user_id' => null, 'voter_2014' => 5, 'voter_2019' => 18, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Lompu', 'village_type' => 'Desa', 'district_id' => 8, 'user_id' => null, 'voter_2014' => 26, 'voter_2019' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Walenreng', 'village_type' => 'Desa', 'district_id' => 8, 'user_id' => null, 'voter_2014' => 38, 'voter_2019' => 28, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Ajang Pulu', 'village_type' => 'Desa', 'district_id' => 8, 'user_id' => null, 'voter_2014' => 33, 'voter_2019' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Padang Loang', 'village_type' => 'Desa', 'district_id' => 8, 'user_id' => null, 'voter_2014' => 19, 'voter_2019' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Abbumpungeng', 'village_type' => 'Desa', 'district_id' => 8, 'user_id' => null, 'voter_2014' => 22, 'voter_2019' => 23, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Kawerang', 'village_type' => 'Desa', 'district_id' => 8, 'user_id' => null, 'voter_2014' => 19, 'voter_2019' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Awo', 'village_type' => 'Desa', 'district_id' => 8, 'user_id' => null, 'voter_2014' => 22, 'voter_2019' => 31, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Kanco', 'village_type' => 'Desa', 'district_id' => 8, 'user_id' => null, 'voter_2014' => 18, 'voter_2019' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Cinennung', 'village_type' => 'Desa', 'district_id' => 8, 'user_id' => null, 'voter_2014' => 17, 'voter_2019' => 79, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Mappesangka', 'village_type' => 'Desa', 'district_id' => 9, 'user_id' => null, 'voter_2014' => 2, 'voter_2019' => 22, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Salebba', 'village_type' => 'Desa', 'district_id' => 9, 'user_id' => null, 'voter_2014' => 16, 'voter_2019' => 72, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Mattampae', 'village_type' => 'Desa', 'district_id' => 9, 'user_id' => null, 'voter_2014' => 1, 'voter_2019' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Pattimpa', 'village_type' => 'Desa', 'district_id' => 9, 'user_id' => null, 'voter_2014' => 9, 'voter_2019' => 18, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Tellu Boccoe', 'village_type' => 'Desa', 'district_id' => 9, 'user_id' => null, 'voter_2014' => 11, 'voter_2019' => 46, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Turu Adae', 'village_type' => 'Desa', 'district_id' => 9, 'user_id' => null, 'voter_2014' => 1, 'voter_2019' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Salampe', 'village_type' => 'Desa', 'district_id' => 9, 'user_id' => null, 'voter_2014' => 2, 'voter_2019' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Poleonro', 'village_type' => 'Desa', 'district_id' => 9, 'user_id' => null, 'voter_2014' => 10, 'voter_2019' => 15, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Bolli', 'village_type' => 'Desa', 'district_id' => 9, 'user_id' => null, 'voter_2014' => 32, 'voter_2019' => 18, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Bulu-Bulu', 'village_type' => 'Desa', 'district_id' => 10, 'user_id' => null, 'voter_2014' => 10, 'voter_2019' => 221, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Gareccing', 'village_type' => 'Desa', 'district_id' => 10, 'user_id' => null, 'voter_2014' => 21, 'voter_2019' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Biccoing', 'village_type' => 'Desa', 'district_id' => 10, 'user_id' => null, 'voter_2014' => 5, 'voter_2019' => 22, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Ujunge', 'village_type' => 'Desa', 'district_id' => 10, 'user_id' => null, 'voter_2014' => 26, 'voter_2019' => 26, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Libureng', 'village_type' => 'Desa', 'district_id' => 10, 'user_id' => null, 'voter_2014' => 38, 'voter_2019' => 25, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Rappa', 'village_type' => 'Desa', 'district_id' => 10, 'user_id' => null, 'voter_2014' => 33, 'voter_2019' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Bacu', 'village_type' => 'Desa', 'district_id' => 10, 'user_id' => null, 'voter_2014' => 19, 'voter_2019' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Muara', 'village_type' => 'Desa', 'district_id' => 10, 'user_id' => null, 'voter_2014' => 22, 'voter_2019' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Bone Pute', 'village_type' => 'Desa', 'district_id' => 10, 'user_id' => null, 'voter_2014' => 19, 'voter_2019' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Pada Tuo', 'village_type' => 'Desa', 'district_id' => 10, 'user_id' => null, 'voter_2014' => 22, 'voter_2019' => 87, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Samaenre', 'village_type' => 'Desa', 'district_id' => 10, 'user_id' => null, 'voter_2014' => 18, 'voter_2019' => 20, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Kahu', 'village_type' => 'Kelurahan', 'district_id' => 11, 'user_id' => null, 'voter_2014' => 339, 'voter_2019' => 279, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => ' Watang Cani', 'village_type' => 'Desa', 'district_id' => 11, 'user_id' => null, 'voter_2014' => 481, 'voter_2019' => 600, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => ' Pattuku', 'village_type' => 'Desa', 'district_id' => 11, 'user_id' => null, 'voter_2014' => 101, 'voter_2019' => 301, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => ' Bontojai', 'village_type' => 'Desa', 'district_id' => 11, 'user_id' => null, 'voter_2014' => 205, 'voter_2019' => 522, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => ' Bana', 'village_type' => 'Desa', 'district_id' => 11, 'user_id' => null, 'voter_2014' => 326, 'voter_2019' => 536, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => ' Pammusureng', 'village_type' => 'Desa', 'district_id' => 11, 'user_id' => null, 'voter_2014' => 294, 'voter_2019' => 308, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => ' Langi', 'village_type' => 'Desa', 'district_id' => 11, 'user_id' => null, 'voter_2014' => 664, 'voter_2019' => 597, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => ' Ere Cinnong', 'village_type' => 'Desa', 'district_id' => 11, 'user_id' => null, 'voter_2014' => 252, 'voter_2019' => 214, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => ' Bulu Sirua', 'village_type' => 'Desa', 'district_id' => 11, 'user_id' => null, 'voter_2014' => 207, 'voter_2019' => 257, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => ' Lamoncong', 'village_type' => 'Desa', 'district_id' => 11, 'user_id' => null, 'voter_2014' => 116, 'voter_2019' => 151, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => ' Mattiro Walie', 'village_type' => 'Desa', 'district_id' => 11, 'user_id' => null, 'voter_2014' => 585, 'voter_2019' => 682, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Palattae', 'village_type' => 'Kelurahan', 'district_id' => 12, 'user_id' => null, 'voter_2014' => 166, 'voter_2019' => 479, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Nusa', 'village_type' => 'Desa', 'district_id' => 12, 'user_id' => null, 'voter_2014' => 27, 'voter_2019' => 154, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Pasaka', 'village_type' => 'Desa', 'district_id' => 12, 'user_id' => null, 'voter_2014' => 174, 'voter_2019' => 272, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Labuaja', 'village_type' => 'Desa', 'district_id' => 12, 'user_id' => null, 'voter_2014' => 167, 'voter_2019' => 210, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Cakkela', 'village_type' => 'Desa', 'district_id' => 12, 'user_id' => null, 'voter_2014' => 125, 'voter_2019' => 187, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Balle', 'village_type' => 'Desa', 'district_id' => 12, 'user_id' => null, 'voter_2014' => 331, 'voter_2019' => 116, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Matajang', 'village_type' => 'Desa', 'district_id' => 12, 'user_id' => null, 'voter_2014' => 58, 'voter_2019' => 117, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Cenrana', 'village_type' => 'Desa', 'district_id' => 12, 'user_id' => null, 'voter_2014' => 162, 'voter_2019' => 239, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Sanrego', 'village_type' => 'Desa', 'district_id' => 12, 'user_id' => null, 'voter_2014' => 536, 'voter_2019' => 437, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Biru', 'village_type' => 'Desa', 'district_id' => 12, 'user_id' => null, 'voter_2014' => 301, 'voter_2019' => 458, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Palakka', 'village_type' => 'Desa', 'district_id' => 12, 'user_id' => null, 'voter_2014' => 148, 'voter_2019' => 114, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Tompong Patu', 'village_type' => 'Desa', 'district_id' => 12, 'user_id' => null, 'voter_2014' => 200, 'voter_2019' => 370, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Hulo', 'village_type' => 'Desa', 'district_id' => 12, 'user_id' => null, 'voter_2014' => 27, 'voter_2019' => 268, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Cammilo', 'village_type' => 'Desa', 'district_id' => 12, 'user_id' => null, 'voter_2014' => 72, 'voter_2019' => 121, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Carima', 'village_type' => 'Desa', 'district_id' => 12, 'user_id' => null, 'voter_2014' => 46, 'voter_2019' => 157, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Mattoanging', 'village_type' => 'Desa', 'district_id' => 12, 'user_id' => null, 'voter_2014' => 38, 'voter_2019' => 105, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Arallae', 'village_type' => 'Desa', 'district_id' => 12, 'user_id' => null, 'voter_2014' => 53, 'voter_2019' => 109, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Bontopadang', 'village_type' => 'Desa', 'district_id' => 12, 'user_id' => null, 'voter_2014' => 207, 'voter_2019' => 226, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Lallepo', 'village_type' => 'Desa', 'district_id' => 12, 'user_id' => null, 'voter_2014' => 21, 'voter_2019' => 20, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Maggenrang', 'village_type' => 'Desa', 'district_id' => 12, 'user_id' => null, 'voter_2014' => 75, 'voter_2019' => 57, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Awang Tangka', 'village_type' => 'Kelurahan', 'district_id' => 13, 'user_id' => null, 'voter_2014' => 52, 'voter_2019' => 66, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Raja', 'village_type' => 'Desa', 'district_id' => 13, 'user_id' => null, 'voter_2014' => 81, 'voter_2019' => 61, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Abbumpungeng', 'village_type' => 'Desa', 'district_id' => 13, 'user_id' => null, 'voter_2014' => 43, 'voter_2019' => 61, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Bulu Tanah', 'village_type' => 'Desa', 'district_id' => 13, 'user_id' => null, 'voter_2014' => 46, 'voter_2019' => 117, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Gona', 'village_type' => 'Desa', 'district_id' => 13, 'user_id' => null, 'voter_2014' => 397, 'voter_2019' => 312, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Buareng', 'village_type' => 'Desa', 'district_id' => 13, 'user_id' => null, 'voter_2014' => 175, 'voter_2019' => 104, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Polewali', 'village_type' => 'Desa', 'district_id' => 13, 'user_id' => null, 'voter_2014' => 85, 'voter_2019' => 80, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Pada Elo', 'village_type' => 'Desa', 'district_id' => 13, 'user_id' => null, 'voter_2014' => 109, 'voter_2019' => 94, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Tarasu', 'village_type' => 'Desa', 'district_id' => 13, 'user_id' => null, 'voter_2014' => 72, 'voter_2019' => 69, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Lemo', 'village_type' => 'Desa', 'district_id' => 13, 'user_id' => null, 'voter_2014' => 28, 'voter_2019' => 236, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Kalero', 'village_type' => 'Desa', 'district_id' => 13, 'user_id' => null, 'voter_2014' => 142, 'voter_2019' => 221, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Lappabosse', 'village_type' => 'Desa', 'district_id' => 13, 'user_id' => null, 'voter_2014' => 128, 'voter_2019' => 136, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Waetuo', 'village_type' => 'Desa', 'district_id' => 13, 'user_id' => null, 'voter_2014' => 71, 'voter_2019' => 65, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Pude', 'village_type' => 'Desa', 'district_id' => 13, 'user_id' => null, 'voter_2014' => 91, 'voter_2019' => 23, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Massangkae', 'village_type' => 'Desa', 'district_id' => 13, 'user_id' => null, 'voter_2014' => 49, 'voter_2019' => 74, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Mallahae', 'village_type' => 'Desa', 'district_id' => 13, 'user_id' => null, 'voter_2014' => 68, 'voter_2019' => 103, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Angkue', 'village_type' => 'Desa', 'district_id' => 13, 'user_id' => null, 'voter_2014' => 43, 'voter_2019' => 29, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Ancu', 'village_type' => 'Desa', 'district_id' => 13, 'user_id' => null, 'voter_2014' => 74, 'voter_2019' => 58, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Pancaitana', 'village_type' => 'Kelurahan', 'district_id' => 14, 'user_id' => null, 'voter_2014' => 57, 'voter_2019' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Mallimongeng', 'village_type' => 'Desa', 'district_id' => 14, 'user_id' => null, 'voter_2014' => 35, 'voter_2019' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Manera', 'village_type' => 'Desa', 'district_id' => 14, 'user_id' => null, 'voter_2014' => 5, 'voter_2019' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Ulu Balang', 'village_type' => 'Desa', 'district_id' => 14, 'user_id' => null, 'voter_2014' => 8, 'voter_2019' => 14, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Gattareng', 'village_type' => 'Desa', 'district_id' => 14, 'user_id' => null, 'voter_2014' => 127, 'voter_2019' => 171, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Bellu', 'village_type' => 'Desa', 'district_id' => 14, 'user_id' => null, 'voter_2014' => 23, 'voter_2019' => 29, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Tebba', 'village_type' => 'Desa', 'district_id' => 14, 'user_id' => null, 'voter_2014' => 2, 'voter_2019' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Mappatoba', 'village_type' => 'Desa', 'district_id' => 14, 'user_id' => null, 'voter_2014' => 5, 'voter_2019' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Tana Batue', 'village_type' => 'Kelurahan', 'district_id' => 15, 'user_id' => null, 'voter_2014' => 4, 'voter_2019' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Tompobulu', 'village_type' => 'Desa', 'district_id' => 15, 'user_id' => null, 'voter_2014' => 238, 'voter_2019' => 193, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Tappale', 'village_type' => 'Desa', 'district_id' => 15, 'user_id' => null, 'voter_2014' => 105, 'voter_2019' => 73, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Polewali', 'village_type' => 'Desa', 'district_id' => 15, 'user_id' => null, 'voter_2014' => 13, 'voter_2019' => 130, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Pitumpidange', 'village_type' => 'Desa', 'district_id' => 15, 'user_id' => null, 'voter_2014' => 40, 'voter_2019' => 64, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Bune', 'village_type' => 'Desa', 'district_id' => 15, 'user_id' => null, 'voter_2014' => 141, 'voter_2019' => 89, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Swadaya', 'village_type' => 'Desa', 'district_id' => 15, 'user_id' => null, 'voter_2014' => 1, 'voter_2019' => 35, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Binuang', 'village_type' => 'Desa', 'district_id' => 15, 'user_id' => null, 'voter_2014' => 6, 'voter_2019' => 42, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Mallinrung', 'village_type' => 'Desa', 'district_id' => 15, 'user_id' => null, 'voter_2014' => 19, 'voter_2019' => 124, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Ceppaga', 'village_type' => 'Desa', 'district_id' => 15, 'user_id' => null, 'voter_2014' => 19, 'voter_2019' => 34, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Baringeng', 'village_type' => 'Desa', 'district_id' => 15, 'user_id' => null, 'voter_2014' => 454, 'voter_2019' => 267, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Mario', 'village_type' => 'Desa', 'district_id' => 15, 'user_id' => null, 'voter_2014' => 23, 'voter_2019' => 61, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Wanua Waru', 'village_type' => 'Desa', 'district_id' => 15, 'user_id' => null, 'voter_2014' => 70, 'voter_2019' => 100, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Mattiro Walie', 'village_type' => 'Desa', 'district_id' => 15, 'user_id' => null, 'voter_2014' => 61, 'voter_2019' => 52, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Poleonro', 'village_type' => 'Desa', 'district_id' => 15, 'user_id' => null, 'voter_2014' => 4, 'voter_2019' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Mattiro Bulu', 'village_type' => 'Desa', 'district_id' => 15, 'user_id' => null, 'voter_2014' => 9, 'voter_2019' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Mattiro Deceng', 'village_type' => 'Desa', 'district_id' => 15, 'user_id' => null, 'voter_2014' => 3, 'voter_2019' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Suwa', 'village_type' => 'Desa', 'district_id' => 15, 'user_id' => null, 'voter_2014' => 26, 'voter_2019' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Laburasseng', 'village_type' => 'Desa', 'district_id' => 15, 'user_id' => null, 'voter_2014' => 51, 'voter_2019' => 259, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Ponre-Ponre', 'village_type' => 'Desa', 'district_id' => 15, 'user_id' => null, 'voter_2014' => 195, 'voter_2019' => 56, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Patimpeng', 'village_type' => 'Desa', 'district_id' => 16, 'user_id' => null, 'voter_2014' => 91, 'voter_2019' => 79, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Latellang', 'village_type' => 'Desa', 'district_id' => 16, 'user_id' => null, 'voter_2014' => 34, 'voter_2019' => 106, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Maddanreng Pulu', 'village_type' => 'Desa', 'district_id' => 16, 'user_id' => null, 'voter_2014' => 13, 'voter_2019' => 69, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Masago', 'village_type' => 'Desa', 'district_id' => 16, 'user_id' => null, 'voter_2014' => 111, 'voter_2019' => 191, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Batu Lappa', 'village_type' => 'Desa', 'district_id' => 16, 'user_id' => null, 'voter_2014' => 100, 'voter_2019' => 263, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Paccing', 'village_type' => 'Desa', 'district_id' => 16, 'user_id' => null, 'voter_2014' => 49, 'voter_2019' => 58, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Massila', 'village_type' => 'Desa', 'district_id' => 16, 'user_id' => null, 'voter_2014' => 53, 'voter_2019' => 134, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Talabangi', 'village_type' => 'Desa', 'district_id' => 16, 'user_id' => null, 'voter_2014' => 49, 'voter_2019' => 25, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Pationgi', 'village_type' => 'Desa', 'district_id' => 16, 'user_id' => null, 'voter_2014' => 7, 'voter_2019' => 153, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Bulu Ulaweng', 'village_type' => 'Desa', 'district_id' => 16, 'user_id' => null, 'voter_2014' => 3, 'voter_2019' => 52, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Mattampa Walie', 'village_type' => 'Desa', 'district_id' => 17, 'user_id' => null, 'voter_2014' => 35, 'voter_2019' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Lili Riattang', 'village_type' => 'Desa', 'district_id' => 17, 'user_id' => null, 'voter_2014' => 9, 'voter_2019' => 33, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Sengeng Palie', 'village_type' => 'Desa', 'district_id' => 17, 'user_id' => null, 'voter_2014' => 7, 'voter_2019' => 72, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Tenri Pakkua', 'village_type' => 'Desa', 'district_id' => 17, 'user_id' => null, 'voter_2014' => 21, 'voter_2019' => 25, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Patangkai', 'village_type' => 'Desa', 'district_id' => 17, 'user_id' => null, 'voter_2014' => 39, 'voter_2019' => 63, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Ujung Lamuru', 'village_type' => 'Desa', 'district_id' => 17, 'user_id' => null, 'voter_2014' => 10, 'voter_2019' => 55, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Pattuku Limpoe', 'village_type' => 'Desa', 'district_id' => 17, 'user_id' => null, 'voter_2014' => 25, 'voter_2019' => 42, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Wae Keccee', 'village_type' => 'Desa', 'district_id' => 17, 'user_id' => null, 'voter_2014' => 9, 'voter_2019' => 22, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Tonrongeng', 'village_type' => 'Desa', 'district_id' => 17, 'user_id' => null, 'voter_2014' => 55, 'voter_2019' => 19, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Lalebata', 'village_type' => 'Kelurahan', 'district_id' => 18, 'user_id' => null, 'voter_2014' => 1, 'voter_2019' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Mattampa Walie', 'village_type' => 'Desa', 'district_id' => 18, 'user_id' => null, 'voter_2014' => 6, 'voter_2019' => 39, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Poleonro', 'village_type' => 'Desa', 'district_id' => 18, 'user_id' => null, 'voter_2014' => 3, 'voter_2019' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Sengeng Palie', 'village_type' => 'Desa', 'district_id' => 18, 'user_id' => null, 'voter_2014' => 6, 'voter_2019' => 26, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Mattampa Bulu', 'village_type' => 'Desa', 'district_id' => 18, 'user_id' => null, 'voter_2014' => 2, 'voter_2019' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Turu Cinnae', 'village_type' => 'Desa', 'district_id' => 18, 'user_id' => null, 'voter_2014' => 35, 'voter_2019' => 18, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Seberang', 'village_type' => 'Desa', 'district_id' => 18, 'user_id' => null, 'voter_2014' => 6, 'voter_2019' => 14, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Massenreng Pulu', 'village_type' => 'Desa', 'district_id' => 18, 'user_id' => null, 'voter_2014' => 10, 'voter_2019' => 26, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Mamminasae', 'village_type' => 'Desa', 'district_id' => 18, 'user_id' => null, 'voter_2014' => 22, 'voter_2019' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Pada Elo', 'village_type' => 'Desa', 'district_id' => 18, 'user_id' => null, 'voter_2014' => 2, 'voter_2019' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Barugae', 'village_type' => 'Desa', 'district_id' => 18, 'user_id' => null, 'voter_2014' => 24, 'voter_2019' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Barakkae', 'village_type' => 'Desa', 'district_id' => 18, 'user_id' => null, 'voter_2014' => 0, 'voter_2019' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Cinnong', 'village_type' => 'Kelurahan', 'district_id' => 19, 'user_id' => null, 'voter_2014' => 171, 'voter_2019' => 19, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Lilina Ajangale', 'village_type' => 'Desa', 'district_id' => 19, 'user_id' => null, 'voter_2014' => 0, 'voter_2019' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Cani Sirenreng', 'village_type' => 'Desa', 'district_id' => 19, 'user_id' => null, 'voter_2014' => 0, 'voter_2019' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Ulaweng Cinnong', 'village_type' => 'Desa', 'district_id' => 19, 'user_id' => null, 'voter_2014' => 0, 'voter_2019' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Pallawa Rukka', 'village_type' => 'Desa', 'district_id' => 19, 'user_id' => null, 'voter_2014' => 0, 'voter_2019' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Jompie', 'village_type' => 'Desa', 'district_id' => 19, 'user_id' => null, 'voter_2014' => 0, 'voter_2019' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Sappe Walie', 'village_type' => 'Desa', 'district_id' => 19, 'user_id' => null, 'voter_2014' => 0, 'voter_2019' => 22, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Lamakkaraseng', 'village_type' => 'Desa', 'district_id' => 19, 'user_id' => null, 'voter_2014' => 0, 'voter_2019' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Mula Menree', 'village_type' => 'Desa', 'district_id' => 19, 'user_id' => null, 'voter_2014' => 0, 'voter_2019' => 19, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Tea Musu', 'village_type' => 'Desa', 'district_id' => 19, 'user_id' => null, 'voter_2014' => 0, 'voter_2019' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Tea Malala', 'village_type' => 'Desa', 'district_id' => 19, 'user_id' => null, 'voter_2014' => 0, 'voter_2019' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Galung', 'village_type' => 'Desa', 'district_id' => 19, 'user_id' => null, 'voter_2014' => 0, 'voter_2019' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Tadang Palie', 'village_type' => 'Desa', 'district_id' => 19, 'user_id' => null, 'voter_2014' => 0, 'voter_2019' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Timusu', 'village_type' => 'Desa', 'district_id' => 19, 'user_id' => null, 'voter_2014' => 0, 'voter_2019' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Manurunge', 'village_type' => 'Desa', 'district_id' => 19, 'user_id' => null, 'voter_2014' => 0, 'voter_2019' => 29, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Lili Riattang', 'village_type' => 'Desa', 'district_id' => 20, 'user_id' => null, 'voter_2014' => 4, 'voter_2019' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Mattaro Purae', 'village_type' => 'Desa', 'district_id' => 20, 'user_id' => null, 'voter_2014' => 5, 'voter_2019' => 23, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Ulaweng Riaja', 'village_type' => 'Desa', 'district_id' => 20, 'user_id' => null, 'voter_2014' => 9, 'voter_2019' => 24, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Waempubue', 'village_type' => 'Desa', 'district_id' => 20, 'user_id' => null, 'voter_2014' => 7, 'voter_2019' => 71, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Waemputange', 'village_type' => 'Desa', 'district_id' => 20, 'user_id' => null, 'voter_2014' => 2, 'voter_2019' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Amali Riattang', 'village_type' => 'Desa', 'district_id' => 20, 'user_id' => null, 'voter_2014' => 1, 'voter_2019' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Tassipi', 'village_type' => 'Desa', 'district_id' => 20, 'user_id' => null, 'voter_2014' => 0, 'voter_2019' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Wellulang', 'village_type' => 'Desa', 'district_id' => 20, 'user_id' => null, 'voter_2014' => 1, 'voter_2019' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Benteng Tellue', 'village_type' => 'Desa', 'district_id' => 20, 'user_id' => null, 'voter_2014' => 0, 'voter_2019' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Tacipong', 'village_type' => 'Desa', 'district_id' => 20, 'user_id' => null, 'voter_2014' => 2, 'voter_2019' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Laponrong', 'village_type' => 'Desa', 'district_id' => 20, 'user_id' => null, 'voter_2014' => 3, 'voter_2019' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Ajang Laleng', 'village_type' => 'Desa', 'district_id' => 20, 'user_id' => null, 'voter_2014' => 11, 'voter_2019' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Tocinnong', 'village_type' => 'Desa', 'district_id' => 20, 'user_id' => null, 'voter_2014' => 2, 'voter_2019' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Bila', 'village_type' => 'Desa', 'district_id' => 20, 'user_id' => null, 'voter_2014' => 3, 'voter_2019' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Mampotu', 'village_type' => 'Kelurahan', 'district_id' => 20, 'user_id' => null, 'voter_2014' => 5, 'voter_2019' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Tellangkere', 'village_type' => 'Desa', 'district_id' => 21, 'user_id' => null, 'voter_2014' => 6, 'voter_2019' => 35, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Lagori', 'village_type' => 'Desa', 'district_id' => 21, 'user_id' => null, 'voter_2014' => 14, 'voter_2019' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Gaya Baru', 'village_type' => 'Desa', 'district_id' => 21, 'user_id' => null, 'voter_2014' => 3, 'voter_2019' => 89, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Tapong', 'village_type' => 'Desa', 'district_id' => 21, 'user_id' => null, 'voter_2014' => 8, 'voter_2019' => 23, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Sadar', 'village_type' => 'Desa', 'district_id' => 21, 'user_id' => null, 'voter_2014' => 4, 'voter_2019' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Tondong', 'village_type' => 'Desa', 'district_id' => 21, 'user_id' => null, 'voter_2014' => 2, 'voter_2019' => 15, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Samaenre', 'village_type' => 'Desa', 'district_id' => 21, 'user_id' => null, 'voter_2014' => 1, 'voter_2019' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Bonto Masunggu', 'village_type' => 'Desa', 'district_id' => 21, 'user_id' => null, 'voter_2014' => 9, 'voter_2019' => 18, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Pallawa', 'village_type' => 'Desa', 'district_id' => 21, 'user_id' => null, 'voter_2014' => 5, 'voter_2019' => 24, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Polewali', 'village_type' => 'Desa', 'district_id' => 21, 'user_id' => null, 'voter_2014' => 13, 'voter_2019' => 23, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Batu Putih', 'village_type' => 'Desa', 'district_id' => 21, 'user_id' => null, 'voter_2014' => 2, 'voter_2019' => 39, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Samaenre', 'village_type' => 'Desa', 'district_id' => 22, 'user_id' => null, 'voter_2014' => 47, 'voter_2019' => 31, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Tungke', 'village_type' => 'Desa', 'district_id' => 22, 'user_id' => null, 'voter_2014' => 35, 'voter_2019' => 71, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Selli', 'village_type' => 'Desa', 'district_id' => 22, 'user_id' => null, 'voter_2014' => 11, 'voter_2019' => 129, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Bengo', 'village_type' => 'Desa', 'district_id' => 22, 'user_id' => null, 'voter_2014' => 39, 'voter_2019' => 25, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Mattaropuli', 'village_type' => 'Desa', 'district_id' => 22, 'user_id' => null, 'voter_2014' => 26, 'voter_2019' => 35, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Lili Riawang', 'village_type' => 'Desa', 'district_id' => 22, 'user_id' => null, 'voter_2014' => 85, 'voter_2019' => 142, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Walimpong', 'village_type' => 'Desa', 'district_id' => 22, 'user_id' => null, 'voter_2014' => 10, 'voter_2019' => 132, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Bulu Allaporenge', 'village_type' => 'Desa', 'district_id' => 22, 'user_id' => null, 'voter_2014' => 14, 'voter_2019' => 35, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Mattiro Walie', 'village_type' => 'Desa', 'district_id' => 22, 'user_id' => null, 'voter_2014' => 17, 'voter_2019' => 66, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Maccope', 'village_type' => 'Kelurahan', 'district_id' => 23, 'user_id' => null, 'voter_2014' => 16, 'voter_2019' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Carebbu', 'village_type' => 'Desa', 'district_id' => 23, 'user_id' => null, 'voter_2014' => 91, 'voter_2019' => 22, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Cumpiga', 'village_type' => 'Desa', 'district_id' => 23, 'user_id' => null, 'voter_2014' => 12, 'voter_2019' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Paccing', 'village_type' => 'Desa', 'district_id' => 23, 'user_id' => null, 'voter_2014' => 12, 'voter_2019' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Lattekko', 'village_type' => 'Desa', 'district_id' => 23, 'user_id' => null, 'voter_2014' => 19, 'voter_2019' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Matuju', 'village_type' => 'Desa', 'district_id' => 23, 'user_id' => null, 'voter_2014' => 18, 'voter_2019' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Unra', 'village_type' => 'Desa', 'district_id' => 23, 'user_id' => null, 'voter_2014' => 13, 'voter_2019' => 46, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Kading', 'village_type' => 'Desa', 'district_id' => 23, 'user_id' => null, 'voter_2014' => 119, 'voter_2019' => 50, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Mallari', 'village_type' => 'Desa', 'district_id' => 23, 'user_id' => null, 'voter_2014' => 284, 'voter_2019' => 177, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Kajuara', 'village_type' => 'Desa', 'district_id' => 23, 'user_id' => null, 'voter_2014' => 156, 'voter_2019' => 64, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Jaling', 'village_type' => 'Desa', 'district_id' => 23, 'user_id' => null, 'voter_2014' => 57, 'voter_2019' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Bulumparee', 'village_type' => 'Desa', 'district_id' => 23, 'user_id' => null, 'voter_2014' => 15, 'voter_2019' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Abbanuang', 'village_type' => 'Desa', 'district_id' => 23, 'user_id' => null, 'voter_2014' => 174, 'voter_2019' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Lappo Ase', 'village_type' => 'Desa', 'district_id' => 23, 'user_id' => null, 'voter_2014' => 33, 'voter_2019' => 15, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Awo Lagading', 'village_type' => 'Desa', 'district_id' => 23, 'user_id' => null, 'voter_2014' => 6, 'voter_2019' => 25, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Carigading', 'village_type' => 'Desa', 'district_id' => 23, 'user_id' => null, 'voter_2014' => 27, 'voter_2019' => 80, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Cakke Bone', 'village_type' => 'Desa', 'district_id' => 23, 'user_id' => null, 'voter_2014' => 11, 'voter_2019' => 15, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Mappalo Ulaweng', 'village_type' => 'Desa', 'district_id' => 23, 'user_id' => null, 'voter_2014' => 43, 'voter_2019' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Otting', 'village_type' => 'Kelurahan', 'district_id' => 24, 'user_id' => null, 'voter_2014' => 4, 'voter_2019' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Tokaseng', 'village_type' => 'Kelurahan', 'district_id' => 24, 'user_id' => null, 'voter_2014' => 38, 'voter_2019' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Palongki', 'village_type' => 'Desa', 'district_id' => 24, 'user_id' => null, 'voter_2014' => 3, 'voter_2019' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Tajong', 'village_type' => 'Desa', 'district_id' => 24, 'user_id' => null, 'voter_2014' => 3, 'voter_2019' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Ulo', 'village_type' => 'Desa', 'district_id' => 24, 'user_id' => null, 'voter_2014' => 81, 'voter_2019' => 41, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Lanca', 'village_type' => 'Desa', 'district_id' => 24, 'user_id' => null, 'voter_2014' => 113, 'voter_2019' => 33, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Itterung', 'village_type' => 'Desa', 'district_id' => 24, 'user_id' => null, 'voter_2014' => 48, 'voter_2019' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Mattoanging', 'village_type' => 'Desa', 'district_id' => 24, 'user_id' => null, 'voter_2014' => 8, 'voter_2019' => 15, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Lamuru', 'village_type' => 'Desa', 'district_id' => 24, 'user_id' => null, 'voter_2014' => 42, 'voter_2019' => 92, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Waji', 'village_type' => 'Desa', 'district_id' => 24, 'user_id' => null, 'voter_2014' => 55, 'voter_2019' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Ajjalireng', 'village_type' => 'Desa', 'district_id' => 24, 'user_id' => null, 'voter_2014' => 27, 'voter_2019' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Sijelling', 'village_type' => 'Desa', 'district_id' => 24, 'user_id' => null, 'voter_2014' => 37, 'voter_2019' => 20, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Lea', 'village_type' => 'Desa', 'district_id' => 24, 'user_id' => null, 'voter_2014' => 1, 'voter_2019' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Pada Idi', 'village_type' => 'Desa', 'district_id' => 24, 'user_id' => null, 'voter_2014' => 0, 'voter_2019' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Pongka', 'village_type' => 'Desa', 'district_id' => 24, 'user_id' => null, 'voter_2014' => 14, 'voter_2019' => 14, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Lappae', 'village_type' => 'Desa', 'district_id' => 24, 'user_id' => null, 'voter_2014' => 97, 'voter_2019' => 37, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Patangnga', 'village_type' => 'Desa', 'district_id' => 24, 'user_id' => null, 'voter_2014' => 12, 'voter_2019' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Pompanua', 'village_type' => 'Desa', 'district_id' => 25, 'user_id' => null, 'voter_2014' => 110, 'voter_2019' => 62, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Welado', 'village_type' => 'Desa', 'district_id' => 25, 'user_id' => null, 'voter_2014' => 15, 'voter_2019' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Pinceng Pute', 'village_type' => 'Desa', 'district_id' => 25, 'user_id' => null, 'voter_2014' => 37, 'voter_2019' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Opo', 'village_type' => 'Desa', 'district_id' => 25, 'user_id' => null, 'voter_2014' => 35, 'voter_2019' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Labissa', 'village_type' => 'Desa', 'district_id' => 25, 'user_id' => null, 'voter_2014' => 12, 'voter_2019' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Timurung', 'village_type' => 'Desa', 'district_id' => 25, 'user_id' => null, 'voter_2014' => 7, 'voter_2019' => 63, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Leppangeng', 'village_type' => 'Desa', 'district_id' => 25, 'user_id' => null, 'voter_2014' => 10, 'voter_2019' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Allamungeng Patue', 'village_type' => 'Desa', 'district_id' => 25, 'user_id' => null, 'voter_2014' => 3, 'voter_2019' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Amessangeng', 'village_type' => 'Desa', 'district_id' => 25, 'user_id' => null, 'voter_2014' => 10, 'voter_2019' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Lebbae', 'village_type' => 'Desa', 'district_id' => 25, 'user_id' => null, 'voter_2014' => 71, 'voter_2019' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Manciri', 'village_type' => 'Desa', 'district_id' => 25, 'user_id' => null, 'voter_2014' => 70, 'voter_2019' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Telle', 'village_type' => 'Desa', 'district_id' => 25, 'user_id' => null, 'voter_2014' => 38, 'voter_2019' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Pacciro', 'village_type' => 'Desa', 'district_id' => 25, 'user_id' => null, 'voter_2014' => 32, 'voter_2019' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Pompanua Riattang', 'village_type' => 'Desa', 'district_id' => 25, 'user_id' => null, 'voter_2014' => 35, 'voter_2019' => 37, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Unnyi', 'village_type' => 'Kelurahan', 'district_id' => 26, 'user_id' => null, 'voter_2014' => 7, 'voter_2019' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Mario', 'village_type' => 'Desa', 'district_id' => 26, 'user_id' => null, 'voter_2014' => 20, 'voter_2019' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Laccori', 'village_type' => 'Desa', 'district_id' => 26, 'user_id' => null, 'voter_2014' => 12, 'voter_2019' => 18, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Pattiro', 'village_type' => 'Desa', 'district_id' => 26, 'user_id' => null, 'voter_2014' => 8, 'voter_2019' => 25, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Cabbeng', 'village_type' => 'Desa', 'district_id' => 26, 'user_id' => null, 'voter_2014' => 34, 'voter_2019' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Panyili', 'village_type' => 'Desa', 'district_id' => 26, 'user_id' => null, 'voter_2014' => 14, 'voter_2019' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Sanrangeng', 'village_type' => 'Desa', 'district_id' => 26, 'user_id' => null, 'voter_2014' => 4, 'voter_2019' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Sailong', 'village_type' => 'Desa', 'district_id' => 26, 'user_id' => null, 'voter_2014' => 2, 'voter_2019' => 41, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Melle', 'village_type' => 'Desa', 'district_id' => 26, 'user_id' => null, 'voter_2014' => 4, 'voter_2019' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Pakkasalo', 'village_type' => 'Desa', 'district_id' => 26, 'user_id' => null, 'voter_2014' => 12, 'voter_2019' => 26, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Tawaroe', 'village_type' => 'Desa', 'district_id' => 26, 'user_id' => null, 'voter_2014' => 17, 'voter_2019' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Uloe', 'village_type' => 'Desa', 'district_id' => 26, 'user_id' => null, 'voter_2014' => 25, 'voter_2019' => 28, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Ujung', 'village_type' => 'Desa', 'district_id' => 26, 'user_id' => null, 'voter_2014' => 5, 'voter_2019' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Padacengnga', 'village_type' => 'Desa', 'district_id' => 26, 'user_id' => null, 'voter_2014' => 5, 'voter_2019' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Lallatang', 'village_type' => 'Desa', 'district_id' => 26, 'user_id' => null, 'voter_2014' => 38, 'voter_2019' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Kampoti', 'village_type' => 'Desa', 'district_id' => 26, 'user_id' => null, 'voter_2014' => 16, 'voter_2019' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Paraja Maju', 'village_type' => 'Desa', 'district_id' => 26, 'user_id' => null, 'voter_2014' => 89, 'voter_2019' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Tocina', 'village_type' => 'Desa', 'district_id' => 26, 'user_id' => null, 'voter_2014' => 4, 'voter_2019' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Tempe', 'village_type' => 'Desa', 'district_id' => 26, 'user_id' => null, 'voter_2014' => 58, 'voter_2019' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Solo', 'village_type' => 'Desa', 'district_id' => 26, 'user_id' => null, 'voter_2014' => 3, 'voter_2019' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Matajang', 'village_type' => 'Desa', 'district_id' => 26, 'user_id' => null, 'voter_2014' => 4, 'voter_2019' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Watang Padacenga', 'village_type' => 'Desa', 'district_id' => 26, 'user_id' => null, 'voter_2014' => 4, 'voter_2019' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Cenrana', 'village_type' => 'Kelurahan', 'district_id' => 27, 'user_id' => null, 'voter_2014' => 10, 'voter_2019' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Pacubbe', 'village_type' => 'Desa', 'district_id' => 27, 'user_id' => null, 'voter_2014' => 100, 'voter_2019' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Panyiwi', 'village_type' => 'Desa', 'district_id' => 27, 'user_id' => null, 'voter_2014' => 8, 'voter_2019' => 14, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Latonro', 'village_type' => 'Desa', 'district_id' => 27, 'user_id' => null, 'voter_2014' => 25, 'voter_2019' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Watu', 'village_type' => 'Desa', 'district_id' => 27, 'user_id' => null, 'voter_2014' => 10, 'voter_2019' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Nagauleng', 'village_type' => 'Desa', 'district_id' => 27, 'user_id' => null, 'voter_2014' => 34, 'voter_2019' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Awang Cenrana', 'village_type' => 'Desa', 'district_id' => 27, 'user_id' => null, 'voter_2014' => 10, 'voter_2019' => 33, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Pallime', 'village_type' => 'Desa', 'district_id' => 27, 'user_id' => null, 'voter_2014' => 40, 'voter_2019' => 39, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Laoni', 'village_type' => 'Desa', 'district_id' => 27, 'user_id' => null, 'voter_2014' => 19, 'voter_2019' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Cakkeware', 'village_type' => 'Desa', 'district_id' => 27, 'user_id' => null, 'voter_2014' => 10, 'voter_2019' => 19, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Lebongnge', 'village_type' => 'Desa', 'district_id' => 27, 'user_id' => null, 'voter_2014' => 110, 'voter_2019' => 14, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Labotto', 'village_type' => 'Desa', 'district_id' => 27, 'user_id' => null, 'voter_2014' => 184, 'voter_2019' => 42, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Ajallasse', 'village_type' => 'Desa', 'district_id' => 27, 'user_id' => null, 'voter_2014' => 41, 'voter_2019' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Pusungnge', 'village_type' => 'Desa', 'district_id' => 27, 'user_id' => null, 'voter_2014' => 5, 'voter_2019' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Pallae', 'village_type' => 'Desa', 'district_id' => 27, 'user_id' => null, 'voter_2014' => 3, 'voter_2019' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['village_name' => 'Watang Ta\'', 'village_type' => 'Desa', 'district_id' => 27, 'user_id' => null, 'voter_2014' => 44, 'voter_2019' => 3, 'created_at' => now(), 'updated_at' => now()],


        ];
        foreach ($data as $row) {
            Village::create($row);
        };
        Village::where('id', 96)->update(
            [
                'user_id' => 9
            ]
        );
    }
}
